title: Blog
description: Personal blog
baseURL: http://localhost:9000
minify: false
pluralizelisttitles: false
timeZone: Europe/Rome
defaultContentLanguage: it
disableKinds:
  - sitemap
  - robotsTXT
  - RSS
