title: Blog
description: Personal blog
baseURL: http://localhost:9000

pluralizelisttitles: false
timeZone: Europe/Rome
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true

minify: false
disableKinds:
  - sitemap
  - robotsTXT
  - RSS
