en:
  languageCode: en-US
  languageName: English
  title: P4
  weight: 1
  menus:
    main:
      - name: theory
        pageRef: /book/intro
        weight: 1
      - name: test yourself
        pageRef: /test
        weight: 2
      - name: about
        pageRef: /about
        weight: 3

it:
  languageCode: it-IT
  languageName: Italiano
  title: P4
  weight: 2
  menus:
    main:
      - name: teoria
        pageRef: /book/intro
        weight: 1
      - name: completa il test
        pageRef: /test
        weight: 2
      - name: about
        pageRef: /about
        weight: 3
